# Generated by Django 4.0.4 on 2022-04-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_completed', models.IntegerField(default=0)),
                ('Clients', models.IntegerField(default=0)),
                ('coffee', models.IntegerField(default=0)),
                ('real_professional', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('icon', models.CharField(max_length=20)),
                ('descritpion', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
